baseURL = "https://examplesite.com"
disableLanguages = []
disqusShortname = ""
paginate = "9"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "NWE"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[ menu . main ]]
name = " Création de nos étudiants "
pre = "# "
poids = 1
[[ menu . main ]]
name = " Événements "
pre = " #"
url = " portfolio "
poids = 2
[[ menu . main ]]
name = " Faire un don "
pre = " # "
url = " testimonial"
poids = 3
[[ menu . main ]]
name = " Bureau des étudiants "
pre = " # "
url = " team "
poids =   4
[[ menu . main ]]
name = " Parrainer "
pre = " # "
url = " blog "
poids = 5
[[ menu . main ]]
name = " Nos partenaires "
pre = " # "
url = " partnair "
poids = 6
[[ menu . main ]]
name = " Cotisation "
pre = " # "
url = " pricing "
poids = 7
[[ menu . main ]]
name = " Contact "
pre = " # "
url = " contact "
poids = 8
[[ menu . main ]]
name = " Faire un don "
pre = " # "
url = " donnation "
poids = 9
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax Hugo Template"
google_analytics_id = ""
logo = "/images/logo_nwe_blanc.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "/images/logo_nwe_blanc.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
